function descr = create_fiji_descriptor(dims, nbits)
    % Create a random 5D matrix for polarization microscopy
    %
    % Inputs:
    %   * dims: 5D vector of integers, defining the dimensions of the
    %   matrix [nrows, ncols, nchans, nzplanes, npolar]
    %   * nbits: number of bytes of the uint 5D matrix

    arguments
        dims (1,5) uint32 = [300, 400, 4, 10, 20]
        nbits (1,1) double = 16
    end

    descr = ['ImageJ=1.52p' newline ...
            'images=' num2str(dims(3)*...
                              dims(4)*...
                              dims(5)) newline... 
            'channels=' num2str(dims(3)) newline...
            'slices=' num2str(dims(4)) newline...
            'frames=' num2str(dims(5)) newline... 
            'hyperstack=true' newline...
            'mode=grayscale' newline...  
            'loop=false' newline...  
            'min=0.0' newline...      
            'max=' num2str(2^nbits-1) '.0'];
end

